import type { Locale } from '../types/athlete';

export const messages = {
  en: {
    brandTagline:'Shift your training forward.',welcomeTitle:'Let’s build your profile',welcomeBody:'A few details help RepShift shape training around your body, experience and preferences.',language:'Language',username:'Username',firstName:'First name',lastName:'Last name',preferredName:'What should RepShift call you?',birthDate:'Date of birth',height:'Height',weight:'Body weight',units:'Units',metric:'Metric',imperial:'Imperial',kg:'kg',lb:'lb',cm:'cm',ftIn:'ft / in',saveProfile:'Continue',updateProfile:'Save changes',required:'This field is required.',invalidUsername:'Use 3–20 letters, numbers or underscores.',saved:'Changes saved.',greeting:'Welcome back, {name}.',homeMessage:'Your setup is taking shape. Configure your real loading options so RepShift can suggest weights you can actually build.',editProfile:'Edit profile',profileSetup:'ATHLETE PROFILE',privacyNote:'Your personal details remain private unless you choose to share them in future community features.',menu:'Menu',settings:'Settings',appearance:'Appearance',themeSystem:'Use device setting',themeLight:'Light',themeDark:'Dark',close:'Close',back:'Back',
    equipmentSetup:'Equipment setup',equipmentTitle:'Where do you train?',equipmentBody:'Choose a starting setup, then fine-tune the equipment that is really available to you.',commercialGym:'Commercial gym',commercialGymHint:'Full machine and free-weight access',homeGym:'Home gym',homeGymHint:'Rack, bench and selected weights',minimalSetup:'Minimal setup',minimalSetupHint:'A few versatile essentials',availableEquipment:'Available equipment',selectedCount:'{count} selected',saveEquipment:'Save equipment',editEquipment:'Edit equipment',equipmentReady:'Your training environment is ready.',categoryFreeWeights:'Free weights',categoryMachines:'Machines',categoryCables:'Cables',categoryBodyweight:'Bodyweight',categoryAccessories:'Accessories',equipmentBarbell:'Barbell',equipmentDumbbells:'Dumbbells',equipmentAdjustableDumbbells:'Adjustable dumbbells',equipmentBench:'Bench',equipmentRack:'Rack',equipmentCableStation:'Cable station',equipmentLatPulldown:'Lat pulldown',equipmentLegPress:'Leg press',equipmentLegExtension:'Leg extension',equipmentLegCurl:'Leg curl',equipmentPullupBar:'Pull-up bar',equipmentBands:'Resistance bands',
    loadSetup:'Load setup',loadSetupTitle:'How do you build your weights?',loadSetupBody:'Set your bars, plates and each machine loading system. RepShift will use only combinations you can really load.',loadReady:'Loading options ready',configureLoads:'Configure loads',barbellWeight:'Barbell weight',plateInventory:'Plate inventory',pairsAvailable:'pairs available',pairs:'pairs',dumbbells:'Dumbbells',fixed:'Fixed',adjustable:'Adjustable',both:'Both',dumbbellStep:'Increment',maxDumbbell:'Maximum dumbbell',cableIncrement:'Cable increment',saveLoads:'Save loading setup',plateCalculator:'Barbell load test',targetWeight:'Target weight',perSide:'Per side',achievedWeight:'Achieved',exactMatch:'Exact match',closestBelow:'Closest load below target',
    machineConfiguration:'Machine loading',machineConfigurationHint:'Choose how each machine is loaded. This affects every future weight suggestion.',weightStack:'Weight stack',weightStackHint:'Selector pin or blocks',plateLoaded:'Plate loaded',plateLoadedHint:'Add plates manually',loadIncrement:'Smallest increment',startingResistance:'Empty machine resistance',
    adjustableDumbbellHandle:'Handle weight',includeHandleWeight:'Count handle weight',includeHandleWeightHint:'Turn this on only if you want RepShift to include the handle in the displayed dumbbell weight.',dumbbellPlateCalculator:'Adjustable dumbbell load test',targetPerDumbbell:'Target per dumbbell',perHandleSide:'On each side of each handle',fourPlateRule:'Only plate combinations available for both dumbbells are used.',targetLoad:'Target',availableLoad:'Available load',
  },
  it: {
    brandTagline:'Porta avanti il tuo allenamento.',welcomeTitle:'Costruiamo il tuo profilo',welcomeBody:'Pochi dettagli aiutano RepShift a modellare l’allenamento sul tuo corpo e sulle tue preferenze.',language:'Lingua',username:'Username',firstName:'Nome',lastName:'Cognome',preferredName:'Come deve chiamarti RepShift?',birthDate:'Data di nascita',height:'Altezza',weight:'Peso corporeo',units:'Unità di misura',metric:'Metriche',imperial:'Imperiali',kg:'kg',lb:'lb',cm:'cm',ftIn:'piedi / pollici',saveProfile:'Continua',updateProfile:'Salva modifiche',required:'Questo campo è obbligatorio.',invalidUsername:'Usa 3–20 lettere, numeri o underscore.',saved:'Modifiche salvate.',greeting:'Bentornato, {name}.',homeMessage:'Il tuo setup sta prendendo forma. Configura i carichi reali così RepShift suggerirà solo pesi che puoi davvero montare.',editProfile:'Modifica profilo',profileSetup:'PROFILO ATLETA',privacyNote:'I tuoi dati personali restano privati, salvo tua scelta nelle future funzioni community.',menu:'Menu',settings:'Impostazioni',appearance:'Aspetto',themeSystem:'Segui il dispositivo',themeLight:'Chiaro',themeDark:'Scuro',close:'Chiudi',back:'Indietro',
    equipmentSetup:'Configura attrezzatura',equipmentTitle:'Dove ti alleni?',equipmentBody:'Scegli una configurazione di partenza, poi indica cosa hai davvero a disposizione.',commercialGym:'Palestra completa',commercialGymHint:'Macchinari e pesi liberi completi',homeGym:'Home gym',homeGymHint:'Rack, panca e pesi selezionati',minimalSetup:'Setup essenziale',minimalSetupHint:'Pochi strumenti versatili',availableEquipment:'Attrezzatura disponibile',selectedCount:'{count} selezionati',saveEquipment:'Salva attrezzatura',editEquipment:'Modifica attrezzatura',equipmentReady:'Il tuo ambiente di allenamento è pronto.',categoryFreeWeights:'Pesi liberi',categoryMachines:'Macchinari',categoryCables:'Cavi',categoryBodyweight:'Corpo libero',categoryAccessories:'Accessori',equipmentBarbell:'Bilanciere',equipmentDumbbells:'Manubri',equipmentAdjustableDumbbells:'Manubri regolabili',equipmentBench:'Panca',equipmentRack:'Rack',equipmentCableStation:'Stazione cavi',equipmentLatPulldown:'Lat machine',equipmentLegPress:'Leg press',equipmentLegExtension:'Leg extension',equipmentLegCurl:'Leg curl',equipmentPullupBar:'Sbarra trazioni',equipmentBands:'Elastici',
    loadSetup:'Configurazione carichi',loadSetupTitle:'Come componi i tuoi pesi?',loadSetupBody:'Imposta bilancieri, dischi e il sistema di carico di ogni macchina. RepShift userà solo combinazioni realmente disponibili.',loadReady:'Carichi configurati',configureLoads:'Configura carichi',barbellWeight:'Peso bilanciere',plateInventory:'Parco dischi',pairsAvailable:'coppie disponibili',pairs:'coppie',dumbbells:'Manubri',fixed:'Fissi',adjustable:'Regolabili',both:'Entrambi',dumbbellStep:'Incremento',maxDumbbell:'Manubrio massimo',cableIncrement:'Incremento cavi',saveLoads:'Salva configurazione',plateCalculator:'Prova carico bilanciere',targetWeight:'Peso target',perSide:'Per lato',achievedWeight:'Peso ottenuto',exactMatch:'Combinazione esatta',closestBelow:'Carico disponibile più vicino sotto il target',
    machineConfiguration:'Carico dei macchinari',machineConfigurationHint:'Indica come viene caricato ogni macchinario. Questa scelta influenzerà tutti i suggerimenti futuri.',weightStack:'Pacco pesi',weightStackHint:'Perno o blocchi',plateLoaded:'Carico a dischi',plateLoadedHint:'Dischi caricati a mano',loadIncrement:'Incremento minimo',startingResistance:'Resistenza macchina scarica',
    adjustableDumbbellHandle:'Peso impugnatura',includeHandleWeight:'Considera peso impugnatura',includeHandleWeightHint:'Attivalo solo se vuoi includere il peso dell’impugnatura nel valore mostrato del manubrio.',dumbbellPlateCalculator:'Prova carico manubri regolabili',targetPerDumbbell:'Target per manubrio',perHandleSide:'Su ogni lato di ogni impugnatura',fourPlateRule:'Vengono usate solo combinazioni disponibili contemporaneamente per entrambi i manubri.',targetLoad:'Target',availableLoad:'Carico disponibile',
  },
} as const;

export type MessageKey = keyof typeof messages.en;
export function translate(locale: Locale,key: MessageKey,variables?: Record<string,string>): string { let value:string=messages[locale]?.[key]??messages.en[key]; if(variables) Object.entries(variables).forEach(([name,replacement])=>{value=value.replaceAll(`{${name}}`,replacement)}); return value; }
