import { useMemo, useState } from 'react';
import { exerciseCatalog } from '../data/exerciseCatalog';
import { exerciseContent } from '../data/exerciseContent';
import { getExerciseVisualStages } from '../data/exerciseVisualStages';
import type { EquipmentProfile } from '../types/equipment';
import type { ExerciseDefinition, MovementPattern, MuscleGroup } from '../types/exercise';
import '../exerciseLibrary.css';

interface Props { locale:'it'|'en'; equipmentProfile:EquipmentProfile|null; }

const muscleLabels:Record<MuscleGroup,{it:string;en:string}>={chest:{it:'Petto',en:'Chest'},back:{it:'Schiena',en:'Back'},shoulders:{it:'Spalle',en:'Shoulders'},biceps:{it:'Bicipiti',en:'Biceps'},triceps:{it:'Tricipiti',en:'Triceps'},quadriceps:{it:'Quadricipiti',en:'Quadriceps'},hamstrings:{it:'Femorali',en:'Hamstrings'},glutes:{it:'Glutei',en:'Glutes'},calves:{it:'Polpacci',en:'Calves'},core:{it:'Core',en:'Core'}};
const patternLabels:Record<MovementPattern,{it:string;en:string}>={horizontal_push:{it:'Spinta orizzontale',en:'Horizontal push'},horizontal_pull:{it:'Tirata orizzontale',en:'Horizontal pull'},vertical_push:{it:'Spinta verticale',en:'Vertical push'},vertical_pull:{it:'Tirata verticale',en:'Vertical pull'},squat:{it:'Squat',en:'Squat'},hinge:{it:'Hip hinge',en:'Hip hinge'},lunge:{it:'Affondo',en:'Lunge'},isolation:{it:'Isolamento',en:'Isolation'},carry:{it:'Trasporto',en:'Carry'},core:{it:'Core',en:'Core'}};
const patternIcons:Record<MovementPattern,string>={horizontal_push:'→',horizontal_pull:'←',vertical_push:'↑',vertical_pull:'↓',squat:'▼',hinge:'⌄',lunge:'↘',isolation:'◎',carry:'▣',core:'✣'};
const equipmentLabels:Record<string,{it:string;en:string}>={barbell:{it:'Bilanciere',en:'Barbell'},dumbbells:{it:'Manubri',en:'Dumbbells'},adjustable_dumbbells:{it:'Manubri regolabili',en:'Adjustable dumbbells'},bench:{it:'Panca',en:'Bench'},rack:{it:'Rack',en:'Rack'},cable_station:{it:'Stazione cavi',en:'Cable station'},lat_pulldown:{it:'Lat machine',en:'Lat pulldown'},leg_press:{it:'Leg press',en:'Leg press'},leg_extension:{it:'Leg extension',en:'Leg extension'},leg_curl:{it:'Leg curl',en:'Leg curl'},pullup_bar:{it:'Sbarra trazioni',en:'Pull-up bar'},bands:{it:'Elastici',en:'Bands'}};
const names:Record<string,{it:string;en:string}>={barbell_bench_press:{it:'Panca piana bilanciere',en:'Barbell bench press'},dumbbell_bench_press:{it:'Panca piana manubri',en:'Dumbbell bench press'},push_up:{it:'Piegamenti',en:'Push-up'},overhead_press:{it:'Military press',en:'Overhead press'},dumbbell_shoulder_press:{it:'Shoulder press manubri',en:'Dumbbell shoulder press'},lateral_raise:{it:'Alzate laterali',en:'Lateral raise'},cable_lateral_raise:{it:'Alzate laterali ai cavi',en:'Cable lateral raise'},pull_up:{it:'Trazioni',en:'Pull-up'},lat_pulldown:{it:'Lat machine',en:'Lat pulldown'},barbell_row:{it:'Rematore bilanciere',en:'Barbell row'},one_arm_dumbbell_row:{it:'Rematore con manubrio',en:'One-arm dumbbell row'},cable_row:{it:'Pulley basso',en:'Cable row'},barbell_squat:{it:'Squat bilanciere',en:'Barbell squat'},goblet_squat:{it:'Goblet squat',en:'Goblet squat'},leg_press:{it:'Leg press',en:'Leg press'},romanian_deadlift:{it:'Stacco rumeno',en:'Romanian deadlift'},dumbbell_romanian_deadlift:{it:'Stacco rumeno manubri',en:'Dumbbell Romanian deadlift'},leg_curl:{it:'Leg curl',en:'Leg curl'},leg_extension:{it:'Leg extension',en:'Leg extension'},dumbbell_lunge:{it:'Affondi con manubri',en:'Dumbbell lunge'},barbell_curl:{it:'Curl bilanciere',en:'Barbell curl'},dumbbell_curl:{it:'Curl manubri',en:'Dumbbell curl'},cable_triceps_pushdown:{it:'Pushdown tricipiti',en:'Cable triceps pushdown'},close_grip_push_up:{it:'Piegamenti presa stretta',en:'Close-grip push-up'},standing_calf_raise:{it:'Calf raise in piedi',en:'Standing calf raise'},plank:{it:'Plank',en:'Plank'},dead_bug:{it:'Dead bug',en:'Dead bug'}};

export default function ExerciseLibraryScreen({locale,equipmentProfile}:Props){
 const [query,setQuery]=useState(''); const [muscle,setMuscle]=useState<MuscleGroup|'all'>('all'); const [pattern,setPattern]=useState<MovementPattern|'all'>('all'); const [availableOnly,setAvailableOnly]=useState(true); const [selected,setSelected]=useState<ExerciseDefinition|null>(null);
 const selectedEquipment=equipmentProfile?.selectedEquipmentIds??[];
 const isAvailable=(exercise:ExerciseDefinition)=>exercise.requiredEquipment.every(id=>selectedEquipment.includes(id));
 const missing=(exercise:ExerciseDefinition)=>exercise.requiredEquipment.filter(id=>!selectedEquipment.includes(id));
 const filtered=useMemo(()=>exerciseCatalog.filter(exercise=>{const name=names[exercise.id]?.[locale]??exercise.id.replaceAll('_',' ');return(!query||name.toLowerCase().includes(query.toLowerCase()))&&(muscle==='all'||exercise.primaryMuscle===muscle)&&(pattern==='all'||exercise.movementPattern===pattern)&&(!availableOnly||isAvailable(exercise));}).sort((a,b)=>Number(isAvailable(b))-Number(isAvailable(a))||names[a.id][locale].localeCompare(names[b.id][locale])),[query,muscle,pattern,availableOnly,selectedEquipment.join('|'),locale]);
 const clearFilters=()=>{setQuery('');setMuscle('all');setPattern('all');setAvailableOnly(false)};
 const selectedContent=selected?exerciseContent[selected.id]:null;
 const visualStages=selected?getExerciseVisualStages(selected):[];

 return <section className="exercise-library-screen">
  <div className="exercise-hero"><div><span>{locale==='it'?'LIBRERIA INTELLIGENTE':'SMART LIBRARY'}</span><h1>{locale==='it'?'Trova il movimento giusto':'Find the right movement'}</h1><p>{locale==='it'?'Filtra per muscolo, movimento e attrezzatura realmente disponibile.':'Filter by muscle, movement and equipment you actually have.'}</p></div><strong>{filtered.length}</strong></div>
  <div className="exercise-filter-deck"><div className="exercise-toolbar"><label><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={locale==='it'?'Cerca esercizio':'Search exercise'}/></label><button className={availableOnly?'active':''} onClick={()=>setAvailableOnly(v=>!v)}>{locale==='it'?'Disponibili':'Available'}</button></div>
   <div className="filter-label">{locale==='it'?'GRUPPO MUSCOLARE':'MUSCLE GROUP'}</div><div className="muscle-rail"><button className={muscle==='all'?'active':''} onClick={()=>setMuscle('all')}>{locale==='it'?'Tutti':'All'}</button>{(Object.keys(muscleLabels) as MuscleGroup[]).map(id=><button key={id} className={muscle===id?'active':''} onClick={()=>setMuscle(id)}>{muscleLabels[id][locale]}</button>)}</div>
   <div className="filter-label">{locale==='it'?'MOVIMENTO':'MOVEMENT'}</div><div className="pattern-rail"><button className={pattern==='all'?'active':''} onClick={()=>setPattern('all')}><span>✦</span><small>{locale==='it'?'Tutti':'All'}</small></button>{(Object.keys(patternLabels) as MovementPattern[]).map(id=><button key={id} className={pattern===id?'active':''} onClick={()=>setPattern(id)}><span>{patternIcons[id]}</span><small>{patternLabels[id][locale]}</small></button>)}</div>
  </div>

  {filtered.length?<div className="exercise-list">{filtered.map(exercise=>{const ok=isAvailable(exercise);const content=exerciseContent[exercise.id];return <button key={exercise.id} className={ok?'exercise-card available':'exercise-card unavailable'} onClick={()=>setSelected(exercise)}><span className="exercise-glyph">{exercise.icon}</span><div><small>{muscleLabels[exercise.primaryMuscle][locale]} · {patternLabels[exercise.movementPattern][locale]}</small><strong>{names[exercise.id]?.[locale]}</strong><p>{content?.description[locale]}</p><em>{ok?(locale==='it'?'Pronto nel tuo setup':'Ready in your setup'):`${locale==='it'?'Manca':'Missing'}: ${missing(exercise).map(id=>equipmentLabels[id]?.[locale]??id).join(', ')}`}</em></div><b>›</b></button>})}</div>:<div className="exercise-empty"><span>⌕</span><strong>{locale==='it'?'Nessun esercizio trovato':'No exercises found'}</strong><p>{locale==='it'?'Prova a cambiare muscolo, movimento o disponibilità.':'Try changing muscle, movement or availability.'}</p><button onClick={clearFilters}>{locale==='it'?'Azzera filtri':'Clear filters'}</button></div>}

  {selected&&selectedContent&&<div className="exercise-sheet-backdrop" onClick={()=>setSelected(null)}><article className="exercise-sheet premium-detail" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><button className="exercise-close" onClick={()=>setSelected(null)}>×</button>
   <header className="exercise-detail-header"><div className="exercise-detail-icon">{selected.icon}</div><div><small>{muscleLabels[selected.primaryMuscle][locale]}</small><h2>{names[selected.id]?.[locale]}</h2><div className={isAvailable(selected)?'availability-pill ready':'availability-pill'}>{isAvailable(selected)?(locale==='it'?'Disponibile ora':'Available now'):(locale==='it'?'Attrezzatura mancante':'Missing equipment')}</div></div></header>
   <p className="exercise-description">{selectedContent.description[locale]}</p>
   <div className="visual-stage-section"><div className="visual-stage-heading"><div><small>{locale==='it'?'SEQUENZA VISIVA':'VISUAL SEQUENCE'}</small><strong>{locale==='it'?'Fasi del movimento':'Movement stages'}</strong></div><span>{locale==='it'?'Asset in preparazione':'Assets pending'}</span></div><div className="visual-stage-rail">{visualStages.map((stage,index)=><article className="visual-stage-card" key={stage.id}><div className="visual-placeholder"><span>{index+1}</span><b>{selected.icon}</b><small>{stage.assetKey}</small></div><div><strong>{stage.title[locale]}</strong><p>{stage.cue[locale]}</p></div></article>)}</div></div>
   <div className="detail-grid"><div><small>{locale==='it'?'Movimento':'Movement'}</small><strong>{patternLabels[selected.movementPattern][locale]}</strong></div><div><small>{locale==='it'?'Difficoltà':'Difficulty'}</small><strong>{selected.difficulty}</strong></div></div>
   {missing(selected).length>0&&<div className="missing-box"><small>{locale==='it'?'Serve':'Requires'}</small><strong>{missing(selected).map(id=>equipmentLabels[id]?.[locale]??id).join(' · ')}</strong></div>}
   <div className="guidance-grid"><div className="coach-note"><span>✦</span><div><small>{locale==='it'?'COME ESEGUIRLO':'HOW TO DO IT'}</small><p>{selectedContent.tip[locale]}</p></div></div><div className="mistake-note"><span>!</span><div><small>{locale==='it'?'ERRORE COMUNE':'COMMON MISTAKE'}</small><p>{selectedContent.mistake[locale]}</p></div></div></div>
   {selected.alternativeIds.length>0&&<div className="alternative-list"><small>{locale==='it'?'ALTERNATIVE COMPATIBILI':'COMPATIBLE ALTERNATIVES'}</small>{selected.alternativeIds.map(id=>{const next=exerciseCatalog.find(x=>x.id===id);if(!next)return null;return <button key={id} className={isAvailable(next)?'ready':''} onClick={()=>setSelected(next)}><span>{names[id]?.[locale]??id}<small>{isAvailable(next)?(locale==='it'?'Disponibile':'Available'):(locale==='it'?'Setup incompleto':'Missing setup')}</small></span><b>›</b></button>})}</div>}
  </article></div>}
 </section>;
}