import { useEffect, useMemo, useState } from 'react';
import { exerciseCatalog } from '../data/exerciseCatalog';
import { loadActiveWorkoutSession, loadWorkoutSessions, loadWorkoutTemplates, saveActiveWorkoutSession, saveWorkoutSessions, saveWorkoutTemplates } from '../storage/workoutStorage';
import type { WorkoutExerciseDraft, WorkoutSession, WorkoutTemplate } from '../types/workout';
import '../workoutFlow.css';

interface Props { locale: 'it' | 'en'; onExit: () => void; }
type Mode = 'hub' | 'builder' | 'live' | 'history';

const labels: Record<string,{it:string;en:string}> = {
  barbell_bench_press:{it:'Panca piana bilanciere',en:'Barbell bench press'},dumbbell_bench_press:{it:'Panca piana manubri',en:'Dumbbell bench press'},push_up:{it:'Piegamenti',en:'Push-up'},overhead_press:{it:'Military press',en:'Overhead press'},dumbbell_shoulder_press:{it:'Shoulder press manubri',en:'Dumbbell shoulder press'},lateral_raise:{it:'Alzate laterali',en:'Lateral raise'},pull_up:{it:'Trazioni',en:'Pull-up'},lat_pulldown:{it:'Lat machine',en:'Lat pulldown'},barbell_row:{it:'Rematore bilanciere',en:'Barbell row'},one_arm_dumbbell_row:{it:'Rematore manubrio',en:'One-arm dumbbell row'},barbell_squat:{it:'Squat bilanciere',en:'Barbell squat'},goblet_squat:{it:'Goblet squat',en:'Goblet squat'},leg_press:{it:'Leg press',en:'Leg press'},romanian_deadlift:{it:'Stacco rumeno',en:'Romanian deadlift'},leg_curl:{it:'Leg curl',en:'Leg curl'},leg_extension:{it:'Leg extension',en:'Leg extension'},dumbbell_lunge:{it:'Affondi con manubri',en:'Dumbbell lunge'},dumbbell_curl:{it:'Curl manubri',en:'Dumbbell curl'},cable_triceps_pushdown:{it:'Pushdown tricipiti',en:'Cable triceps pushdown'},plank:{it:'Plank',en:'Plank'}
};
const uid=()=>crypto.randomUUID?.() ?? `${Date.now()}-${Math.random()}`;
const exerciseName=(id:string,locale:'it'|'en')=>labels[id]?.[locale]??id.replaceAll('_',' ');
const newRow=(exerciseId:string):WorkoutExerciseDraft=>({id:uid(),exerciseId,sets:3,targetReps:10,targetLoadKg:20,restSeconds:90});

export default function WorkoutFlow({locale,onExit}:Props){
  const [mode,setMode]=useState<Mode>(()=>loadActiveWorkoutSession()?'live':'hub');
  const [templates,setTemplates]=useState<WorkoutTemplate[]>(()=>loadWorkoutTemplates());
  const [history,setHistory]=useState<WorkoutSession[]>(()=>loadWorkoutSessions());
  const [active,setActive]=useState<WorkoutSession|null>(()=>loadActiveWorkoutSession());
  const [name,setName]=useState(locale==='it'?'Allenamento A':'Workout A');
  const [draft,setDraft]=useState<WorkoutExerciseDraft[]>([]);
  const [pickerOpen,setPickerOpen]=useState(false);
  const [query,setQuery]=useState('');
  const [currentExercise,setCurrentExercise]=useState(0);
  const [rest,setRest]=useState(0);

  useEffect(()=>{ if(rest<=0)return; const timer=window.setInterval(()=>setRest(v=>Math.max(0,v-1)),1000); return()=>clearInterval(timer); },[rest]);
  useEffect(()=>{saveActiveWorkoutSession(active)},[active]);

  const filtered=useMemo(()=>exerciseCatalog.filter(x=>exerciseName(x.id,locale).toLowerCase().includes(query.toLowerCase())).slice(0,30),[query,locale]);
  const updateDraft=(id:string,patch:Partial<WorkoutExerciseDraft>)=>setDraft(rows=>rows.map(row=>row.id===id?{...row,...patch}:row));
  const move=(index:number,delta:number)=>setDraft(rows=>{const next=[...rows];const target=index+delta;if(target<0||target>=next.length)return rows;[next[index],next[target]]=[next[target],next[index]];return next;});
  const saveTemplate=()=>{if(!draft.length)return;const now=new Date().toISOString();const template:WorkoutTemplate={id:uid(),name:name.trim()||'Workout',exercises:draft,createdAt:now,updatedAt:now};const next=[template,...templates];setTemplates(saveWorkoutTemplates(next));setMode('hub');};
  const start=(template:WorkoutTemplate)=>{const session:WorkoutSession={id:uid(),templateId:template.id,templateName:template.name,startedAt:new Date().toISOString(),completedAt:null,status:'active',exercises:template.exercises.map(x=>({exerciseId:x.exerciseId,plannedSets:x.sets,targetReps:x.targetReps,targetLoadKg:x.targetLoadKg,restSeconds:x.restSeconds,completedSets:[]}))};setCurrentExercise(0);setActive(session);setMode('live');};
  const completeSet=(reps:number,loadKg:number,rir:number|null)=>{if(!active)return;const index=currentExercise;const exercise=active.exercises[index];const completed={setNumber:exercise.completedSets.length+1,reps,loadKg,rir,completedAt:new Date().toISOString()};const next={...active,exercises:active.exercises.map((x,i)=>i===index?{...x,completedSets:[...x.completedSets,completed]}:x)};setActive(next);setRest(exercise.restSeconds);if(exercise.completedSets.length+1>=exercise.plannedSets&&index<active.exercises.length-1)setCurrentExercise(index+1);};
  const finish=(status:'completed'|'interrupted')=>{if(!active)return;const done={...active,status,completedAt:new Date().toISOString()};const next=[done,...history];setHistory(saveWorkoutSessions(next));setActive(null);setRest(0);setMode('hub');};
  const duration=(session:WorkoutSession)=>Math.max(1,Math.round(((new Date(session.completedAt??Date.now()).getTime())-new Date(session.startedAt).getTime())/60000));

  if(mode==='builder')return <section className="workout-screen"><div className="workout-top"><button onClick={()=>setMode('hub')}>‹</button><div><small>{locale==='it'?'NUOVA ROUTINE':'NEW ROUTINE'}</small><strong>{locale==='it'?'Costruisci allenamento':'Build workout'}</strong></div><button className="workout-save" onClick={saveTemplate}>✓</button></div><input className="workout-name" value={name} onChange={e=>setName(e.target.value)}/><div className="builder-list">{draft.map((row,index)=><article className="builder-card" key={row.id}><div className="builder-head"><span>{index+1}</span><strong>{exerciseName(row.exerciseId,locale)}</strong><div><button onClick={()=>move(index,-1)}>↑</button><button onClick={()=>move(index,1)}>↓</button><button onClick={()=>setDraft(x=>x.filter(y=>y.id!==row.id))}>×</button></div></div><div className="builder-fields"><label><small>{locale==='it'?'Serie':'Sets'}</small><input type="number" min="1" max="10" value={row.sets} onChange={e=>updateDraft(row.id,{sets:Number(e.target.value)})}/></label><label><small>Reps</small><input type="number" min="1" max="50" value={row.targetReps} onChange={e=>updateDraft(row.id,{targetReps:Number(e.target.value)})}/></label><label><small>Kg</small><input type="number" min="0" step="0.5" value={row.targetLoadKg} onChange={e=>updateDraft(row.id,{targetLoadKg:Number(e.target.value)})}/></label><label><small>{locale==='it'?'Recupero':'Rest'}</small><input type="number" min="15" step="15" value={row.restSeconds} onChange={e=>updateDraft(row.id,{restSeconds:Number(e.target.value)})}/></label></div></article>)}</div><button className="add-exercise" onClick={()=>setPickerOpen(true)}>＋ {locale==='it'?'Aggiungi esercizio':'Add exercise'}</button>{pickerOpen&&<div className="workout-sheet-backdrop" onClick={()=>setPickerOpen(false)}><section className="workout-picker" onClick={e=>e.stopPropagation()}><div className="sheet-handle"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={locale==='it'?'Cerca esercizio':'Search exercise'}/>{filtered.map(ex=><button key={ex.id} onClick={()=>{setDraft(rows=>[...rows,newRow(ex.id)]);setPickerOpen(false);setQuery('')}}><span>{ex.icon}</span><strong>{exerciseName(ex.id,locale)}</strong><b>＋</b></button>)}</section></div>}</section>;

  if(mode==='live'&&active){const exercise=active.exercises[currentExercise];const last=exercise.completedSets.at(-1);return <section className="live-workout"><div className="live-header"><div><small>{active.templateName}</small><strong>{currentExercise+1}/{active.exercises.length}</strong></div><button onClick={()=>finish('interrupted')}>{locale==='it'?'Interrompi':'Stop'}</button></div><div className="live-hero"><span>{exerciseCatalog.find(x=>x.id===exercise.exerciseId)?.icon??'◆'}</span><small>{locale==='it'?'ESERCIZIO ATTUALE':'CURRENT EXERCISE'}</small><h1>{exerciseName(exercise.exerciseId,locale)}</h1><p>{exercise.completedSets.length}/{exercise.plannedSets} {locale==='it'?'serie completate':'sets completed'}</p></div>{rest>0&&<div className="rest-timer"><small>{locale==='it'?'RECUPERO':'REST'}</small><strong>{Math.floor(rest/60)}:{String(rest%60).padStart(2,'0')}</strong><button onClick={()=>setRest(0)}>{locale==='it'?'Salta':'Skip'}</button></div>}<SetLogger defaultReps={last?.reps??exercise.targetReps} defaultLoad={last?.loadKg??exercise.targetLoadKg} locale={locale} onComplete={completeSet}/><div className="live-progress">{active.exercises.map((x,i)=><button key={x.exerciseId+i} className={i===currentExercise?'active':x.completedSets.length>=x.plannedSets?'done':''} onClick={()=>setCurrentExercise(i)}>{i+1}</button>)}</div><button className="finish-workout" onClick={()=>finish('completed')}>✓ {locale==='it'?'Completa allenamento':'Complete workout'}</button></section>}

  if(mode==='history')return <section className="workout-screen"><div className="workout-top"><button onClick={()=>setMode('hub')}>‹</button><div><small>{locale==='it'?'DIARIO':'HISTORY'}</small><strong>{locale==='it'?'Allenamenti recenti':'Recent workouts'}</strong></div><i/></div><div className="history-list">{history.length?history.map(item=><article key={item.id}><span>{item.status==='completed'?'✓':'×'}</span><div><strong>{item.templateName}</strong><small>{new Date(item.startedAt).toLocaleDateString(locale)} · {duration(item)} min · {item.exercises.reduce((s,x)=>s+x.completedSets.length,0)} set</small></div></article>):<div className="empty-workout">{locale==='it'?'Nessun allenamento registrato.':'No workouts recorded yet.'}</div>}</div></section>;

  return <section className="workout-hub"><div className="workout-hero"><small>REPSHIFT LIVE</small><h1>{locale==='it'?'Pronto ad allenarti?':'Ready to train?'}</h1><p>{locale==='it'?'Crea una routine, avviala e registra ogni serie senza uscire dal flusso.':'Build a routine, start it and log every set without leaving the flow.'}</p><button onClick={()=>{setDraft([]);setMode('builder')}}>＋ {locale==='it'?'Crea allenamento':'Create workout'}</button></div>{active&&<button className="resume-card" onClick={()=>setMode('live')}><span>▶</span><div><small>{locale==='it'?'SESSIONE IN CORSO':'ACTIVE SESSION'}</small><strong>{active.templateName}</strong></div><b>›</b></button>}<div className="workout-section-title"><strong>{locale==='it'?'Le tue routine':'Your routines'}</strong><button onClick={()=>setMode('history')}>{locale==='it'?'Storico':'History'} ›</button></div><div className="template-list">{templates.map(template=><article key={template.id}><div><small>{template.exercises.length} {locale==='it'?'esercizi':'exercises'}</small><strong>{template.name}</strong><em>{template.exercises.slice(0,3).map(x=>exerciseName(x.exerciseId,locale)).join(' · ')}</em></div><button onClick={()=>start(template)}>▶</button></article>)}{!templates.length&&<div className="empty-workout"><span>✦</span><strong>{locale==='it'?'Nessuna routine ancora':'No routines yet'}</strong><small>{locale==='it'?'Creane una in meno di un minuto.':'Build one in under a minute.'}</small></div>}</div><button className="workout-exit" onClick={onExit}>{locale==='it'?'Torna alla Home':'Back to Home'}</button></section>;
}

function SetLogger({defaultReps,defaultLoad,locale,onComplete}:{defaultReps:number;defaultLoad:number;locale:'it'|'en';onComplete:(reps:number,load:number,rir:number|null)=>void}){
 const [reps,setReps]=useState(defaultReps);const [load,setLoad]=useState(defaultLoad);const [rir,setRir]=useState<number|null>(2);
 useEffect(()=>{setReps(defaultReps);setLoad(defaultLoad)},[defaultReps,defaultLoad]);
 return <div className="set-logger"><div className="set-value"><small>REPS</small><div><button onClick={()=>setReps(v=>Math.max(1,v-1))}>−</button><strong>{reps}</strong><button onClick={()=>setReps(v=>v+1)}>＋</button></div></div><div className="set-value"><small>KG</small><div><button onClick={()=>setLoad(v=>Math.max(0,v-0.5))}>−</button><strong>{load}</strong><button onClick={()=>setLoad(v=>v+0.5)}>＋</button></div></div><div className="rir-row"><small>RIR</small>{[0,1,2,3,4].map(v=><button key={v} className={rir===v?'active':''} onClick={()=>setRir(v)}>{v}</button>)}</div><button className="log-set" onClick={()=>onComplete(reps,load,rir)}>✓ {locale==='it'?'Registra serie':'Log set'}</button></div>
}
