import { FormEvent, useEffect, useMemo, useState } from 'react';
import LoadSetupScreen from './components/LoadSetupScreen';
import { equipmentCatalog, equipmentPresets } from './data/equipmentCatalog';
import { translate } from './i18n/messages';
import { loadEquipmentProfile, saveEquipmentProfile } from './storage/equipmentStorage';
import { loadLoadSetup, saveLoadSetup } from './storage/loadSetupStorage';
import { loadLocale, loadProfile, saveLocale, saveProfile } from './storage/profileStorage';
import type { AthleteProfile, AthleteProfileDraft, Locale, UnitSystem } from './types/athlete';
import type { EquipmentCategory, EquipmentProfile } from './types/equipment';
import type { LoadSetupProfile } from './types/loadSetup';
import './styles.css';

type ThemePreference = 'system' | 'light' | 'dark';
type View = 'home' | 'profile' | 'equipment' | 'loads';
const THEME_KEY = 'repshift.theme.v1';
const emptyDraft = (locale: Locale): AthleteProfileDraft => ({ username:'',firstName:'',lastName:'',preferredName:'',displayName:'',birthDate:'',heightCm:175,bodyWeightKg:75,locale,unitSystem:'metric' });
function profileToDraft(profile: AthleteProfile): AthleteProfileDraft { const { id:_id,createdAt:_createdAt,updatedAt:_updatedAt,schemaVersion:_schemaVersion,revision:_revision,syncState:_syncState,...draft }=profile; return draft; }
const kgToLb=(kg:number)=>Math.round(kg*2.20462); const lbToKg=(lb:number)=>Math.round((lb/2.20462)*10)/10; const cmToFeetInches=(cm:number)=>{const inches=Math.round(cm/2.54);return{feet:Math.floor(inches/12),inches:inches%12}};

export default function App(){
  const initialProfile=useMemo(()=>loadProfile(),[]); const initialEquipment=useMemo(()=>loadEquipmentProfile(),[]); const initialLoads=useMemo(()=>loadLoadSetup(),[]);
  const [locale,setLocale]=useState<Locale>(initialProfile?.locale??loadLocale()); const [profile,setProfile]=useState<AthleteProfile|null>(initialProfile); const [equipmentProfile,setEquipmentProfile]=useState<EquipmentProfile|null>(initialEquipment); const [loadProfile,setLoadProfile]=useState<LoadSetupProfile|null>(initialLoads);
  const [view,setView]=useState<View>(initialProfile?'home':'profile'); const [draft,setDraft]=useState<AthleteProfileDraft>(()=>initialProfile?profileToDraft(initialProfile):emptyDraft(locale)); const [selectedEquipment,setSelectedEquipment]=useState<string[]>(initialEquipment?.selectedEquipmentIds??[]); const [environment,setEnvironment]=useState<EquipmentProfile['environment']>(initialEquipment?.environment??'commercial_gym'); const [errors,setErrors]=useState<Record<string,string>>({}); const [saved,setSaved]=useState(false); const [menuOpen,setMenuOpen]=useState(false); const [theme,setTheme]=useState<ThemePreference>(()=>(localStorage.getItem(THEME_KEY) as ThemePreference)||'system');
  const t=(key:Parameters<typeof translate>[1],variables?:Record<string,string>)=>translate(locale,key,variables); const coachName=profile?.preferredName.trim()||profile?.firstName.trim()||profile?.username||'';
  useEffect(()=>{document.documentElement.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):theme;localStorage.setItem(THEME_KEY,theme)},[theme]);
  const changeLocale=(next:Locale)=>{setLocale(next);saveLocale(next);setDraft(c=>({...c,locale:next}))}; const updateField=<K extends keyof AthleteProfileDraft>(key:K,value:AthleteProfileDraft[K])=>{setSaved(false);setDraft(c=>({...c,[key]:value}))}; const changeUnits=(u:UnitSystem)=>updateField('unitSystem',u); const adjustHeight=(d:number)=>updateField('heightCm',Math.min(230,Math.max(120,(draft.heightCm??175)+d))); const adjustWeight=(d:number)=>updateField('bodyWeightKg',Math.round(Math.min(250,Math.max(35,(draft.bodyWeightKg??75)+d))*10)/10);
  const submitProfile=(e:FormEvent)=>{e.preventDefault();const next:Record<string,string>={};if(!draft.username.trim())next.username=t('required');else if(!/^[a-zA-Z0-9_]{3,20}$/.test(draft.username.trim()))next.username=t('invalidUsername');if(!draft.firstName.trim())next.firstName=t('required');if(!draft.birthDate)next.birthDate=t('required');setErrors(next);if(Object.keys(next).length)return;const p=saveProfile({...draft,username:draft.username.trim(),firstName:draft.firstName.trim(),lastName:draft.lastName.trim(),preferredName:draft.preferredName.trim(),displayName:draft.displayName.trim()||draft.username.trim(),locale},profile);setProfile(p);setDraft(profileToDraft(p));setView('home');setSaved(true)};
  const selectPreset=(env:EquipmentProfile['environment'])=>{setEnvironment(env);setSelectedEquipment([...equipmentPresets[env]])}; const toggleEquipment=(id:string)=>setSelectedEquipment(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id]); const saveEquipment=()=>{const next=saveEquipmentProfile(selectedEquipment,environment,equipmentProfile);setEquipmentProfile(next);setView('home');setSaved(true)};
  const heightLabel=draft.unitSystem==='metric'?`${draft.heightCm??175} ${t('cm')}`:(()=>{const v=cmToFeetInches(draft.heightCm??175);return`${v.feet}′ ${v.inches}″`})(); const weightLabel=draft.unitSystem==='metric'?`${draft.bodyWeightKg??75} ${t('kg')}`:`${kgToLb(draft.bodyWeightKg??75)} ${t('lb')}`; const categories:EquipmentCategory[]=['free_weights','machines','cables','bodyweight','accessories']; const categoryKey:Record<EquipmentCategory,Parameters<typeof translate>[1]>={free_weights:'categoryFreeWeights',machines:'categoryMachines',cables:'categoryCables',bodyweight:'categoryBodyweight',accessories:'categoryAccessories'};
  return <main className="app-shell"><header className="topbar"><button className="brand-lockup" onClick={()=>profile&&setView('home')}><div className="brand-mark">RS</div><strong>RepShift</strong></button><button className="icon-button" aria-label={t('menu')} onClick={()=>setMenuOpen(true)}><span></span><span></span><span></span></button></header>
    {view==='home'&&profile&&<section className="hero-card home-card"><span className="eyebrow">REPSHIFT</span><h1>{t('greeting',{name:coachName})}</h1><p>{t('homeMessage')}</p><div className="profile-summary"><div><span>@{profile.username}</span><small>{profile.firstName} {profile.lastName}</small></div><div><span>{profile.unitSystem==='metric'?`${profile.bodyWeightKg} kg`:`${kgToLb(profile.bodyWeightKg??0)} lb`}</span><small>{profile.unitSystem==='metric'?`${profile.heightCm} cm`:(()=>{const h=cmToFeetInches(profile.heightCm??0);return`${h.feet}′ ${h.inches}″`})()}</small></div></div>
      <button className={equipmentProfile?'feature-card complete':'feature-card'} onClick={()=>setView('equipment')}><span className="feature-icon">⌑</span><div><strong>{equipmentProfile?t('equipmentReady'):t('equipmentSetup')}</strong><small>{equipmentProfile?t('selectedCount',{count:String(equipmentProfile.selectedEquipmentIds.length)}):t('equipmentBody')}</small></div><b>›</b></button>
      <button className={loadProfile?'feature-card complete':'feature-card'} onClick={()=>setView('loads')}><span className="feature-icon">◉</span><div><strong>{loadProfile?t('loadReady'):t('configureLoads')}</strong><small>{loadProfile?`${loadProfile.barbellWeightKg} kg · ${loadProfile.plates.reduce((s,p)=>s+p.quantity,0)} ${t('pairsAvailable')}`:t('loadSetupBody')}</small></div><b>›</b></button>
      {saved&&<div className="success-message">✓ {t('saved')}</div>}<button className="text-button" onClick={()=>setView('profile')}>{t('editProfile')}</button></section>}
    {view==='profile'&&<section className="hero-card"><button className="back-button" onClick={()=>profile?setView('home'):undefined}>‹ {t('back')}</button><span className="eyebrow">{t('profileSetup')}</span><h1>{t('welcomeTitle')}</h1><p>{t('welcomeBody')}</p><form onSubmit={submitProfile} noValidate><div className="form-grid"><label><span>{t('username')} *</span><input value={draft.username} onChange={e=>updateField('username',e.target.value)}/>{errors.username&&<small className="error">{errors.username}</small>}</label><label><span>{t('firstName')} *</span><input value={draft.firstName} onChange={e=>updateField('firstName',e.target.value)}/>{errors.firstName&&<small className="error">{errors.firstName}</small>}</label><label><span>{t('lastName')}</span><input value={draft.lastName} onChange={e=>updateField('lastName',e.target.value)}/></label><label><span>{t('preferredName')}</span><input value={draft.preferredName} onChange={e=>updateField('preferredName',e.target.value)}/></label><label><span>{t('birthDate')} *</span><input type="date" value={draft.birthDate} onChange={e=>updateField('birthDate',e.target.value)}/>{errors.birthDate&&<small className="error">{errors.birthDate}</small>}</label></div><div className="section-label">{t('units')}</div><div className="segmented-control"><button type="button" className={draft.unitSystem==='metric'?'active':''} onClick={()=>changeUnits('metric')}>{t('metric')}<small>kg · cm</small></button><button type="button" className={draft.unitSystem==='imperial'?'active':''} onClick={()=>changeUnits('imperial')}>{t('imperial')}<small>lb · ft</small></button></div><div className="measurement-grid"><div className="measurement-card"><span>{t('height')}</span><strong>{heightLabel}</strong><input type="range" min="120" max="230" value={draft.heightCm??175} onChange={e=>updateField('heightCm',Number(e.target.value))}/><div className="stepper"><button type="button" onClick={()=>adjustHeight(-1)}>−</button><button type="button" onClick={()=>adjustHeight(1)}>+</button></div></div><div className="measurement-card"><span>{t('weight')}</span><strong>{weightLabel}</strong><input type="range" min="35" max="250" step="0.5" value={draft.bodyWeightKg??75} onChange={e=>updateField('bodyWeightKg',Number(e.target.value))}/><div className="stepper"><button type="button" onClick={()=>adjustWeight(draft.unitSystem==='metric'?-0.5:-lbToKg(1))}>−</button><button type="button" onClick={()=>adjustWeight(draft.unitSystem==='metric'?0.5:lbToKg(1))}>+</button></div></div></div><p className="privacy-note">{t('privacyNote')}</p><button className="primary-button" type="submit">{profile?t('updateProfile'):t('saveProfile')}</button></form></section>}
    {view==='equipment'&&<section className="hero-card equipment-screen"><button className="back-button" onClick={()=>setView('home')}>‹ {t('back')}</button><span className="eyebrow">{t('equipmentSetup')}</span><h1>{t('equipmentTitle')}</h1><p>{t('equipmentBody')}</p><div className="preset-grid">{(['commercial_gym','home_gym','minimal'] as const).map(p=><button key={p} className={environment===p?'preset-card selected':'preset-card'} onClick={()=>selectPreset(p)}><span>{p==='commercial_gym'?'◫':p==='home_gym'?'⌂':'◆'}</span><strong>{t(p==='commercial_gym'?'commercialGym':p==='home_gym'?'homeGym':'minimalSetup')}</strong><small>{t(p==='commercial_gym'?'commercialGymHint':p==='home_gym'?'homeGymHint':'minimalSetupHint')}</small></button>)}</div><div className="equipment-heading"><strong>{t('availableEquipment')}</strong><span>{t('selectedCount',{count:String(selectedEquipment.length)})}</span></div>{categories.map(c=><div className="equipment-category" key={c}><h3>{t(categoryKey[c])}</h3><div className="equipment-grid">{equipmentCatalog.filter(i=>i.category===c).map(i=><button key={i.id} className={selectedEquipment.includes(i.id)?'equipment-card selected':'equipment-card'} onClick={()=>toggleEquipment(i.id)}><span className="equipment-symbol">{i.icon}</span><strong>{t(i.nameKey as Parameters<typeof translate>[1])}</strong><span className="checkmark">✓</span></button>)}</div></div>)}<button className="primary-button sticky-action" onClick={saveEquipment}>{t('saveEquipment')}</button></section>}
    {view==='loads'&&<LoadSetupScreen current={loadProfile} t={t} onBack={()=>setView('home')} onSave={draft=>{const next=saveLoadSetup(draft,loadProfile);setLoadProfile(next);setView('home');setSaved(true)}}/>}
    {menuOpen&&<div className="sheet-backdrop" onClick={()=>setMenuOpen(false)}><section className="settings-sheet" onClick={e=>e.stopPropagation()}><div className="sheet-handle"></div><div className="sheet-title"><h2>{t('settings')}</h2><button onClick={()=>setMenuOpen(false)}>×</button></div><div className="setting-block"><span>{t('language')}</span><div className="option-list"><button className={locale==='it'?'selected':''} onClick={()=>changeLocale('it')}>Italiano</button><button className={locale==='en'?'selected':''} onClick={()=>changeLocale('en')}>English</button></div></div><div className="setting-block"><span>{t('appearance')}</span><div className="option-list"><button className={theme==='system'?'selected':''} onClick={()=>setTheme('system')}>{t('themeSystem')}</button><button className={theme==='light'?'selected':''} onClick={()=>setTheme('light')}>{t('themeLight')}</button><button className={theme==='dark'?'selected':''} onClick={()=>setTheme('dark')}>{t('themeDark')}</button></div></div></section></div>}
  </main>
}
