import { FormEvent, useEffect, useMemo, useState } from 'react';
import ConfigurationHub from './components/ConfigurationHub';
import LoadSetupScreen from './components/LoadSetupScreen';
import WorkoutFlow from './components/WorkoutFlow';
import { equipmentCatalog, equipmentPresets } from './data/equipmentCatalog';
import { translate } from './i18n/messages';
import { loadEquipmentProfile, saveEquipmentProfile } from './storage/equipmentStorage';
import { loadLoadSetup, saveLoadSetup } from './storage/loadSetupStorage';
import { loadLocale, loadProfile, saveLocale, saveProfile } from './storage/profileStorage';
import type { AthleteProfile, AthleteProfileDraft, Locale, UnitSystem } from './types/athlete';
import type { EquipmentCategory, EquipmentProfile } from './types/equipment';
import type { LoadSetupProfile } from './types/loadSetup';
import './styles.css';
import './mobileAppShell.css';
import './configurationHub.css';

 type ThemePreference = 'system' | 'light' | 'dark';
 type View = 'home' | 'workout' | 'configuration' | 'profile' | 'equipment' | 'loads';
 const THEME_KEY = 'repshift.theme.v1';
 const emptyDraft = (locale: Locale): AthleteProfileDraft => ({ username:'',firstName:'',lastName:'',preferredName:'',displayName:'',birthDate:'',heightCm:175,bodyWeightKg:75,locale,unitSystem:'metric' });
 function profileToDraft(profile: AthleteProfile): AthleteProfileDraft { const { id:_id,createdAt:_createdAt,updatedAt:_updatedAt,schemaVersion:_schemaVersion,revision:_revision,syncState:_syncState,...draft }=profile; return draft; }
 const kgToLb=(kg:number)=>Math.round(kg*2.20462); const lbToKg=(lb:number)=>Math.round((lb/2.20462)*10)/10; const cmToFeetInches=(cm:number)=>{const inches=Math.round(cm/2.54);return{feet:Math.floor(inches/12),inches:inches%12}};

 export default function App(){
   const initialProfile=useMemo(()=>loadProfile(),[]); const initialEquipment=useMemo(()=>loadEquipmentProfile(),[]); const initialLoads=useMemo(()=>loadLoadSetup(),[]);
   const [locale,setLocale]=useState<Locale>(initialProfile?.locale??loadLocale()); const [profile,setProfile]=useState<AthleteProfile|null>(initialProfile); const [equipmentProfile,setEquipmentProfile]=useState<EquipmentProfile|null>(initialEquipment); const [loadSetupProfile,setLoadSetupProfile]=useState<LoadSetupProfile|null>(initialLoads);
   const [view,setView]=useState<View>(initialProfile?'home':'profile'); const [draft,setDraft]=useState<AthleteProfileDraft>(()=>initialProfile?profileToDraft(initialProfile):emptyDraft(locale)); const [selectedEquipment,setSelectedEquipment]=useState<string[]>(initialEquipment?.selectedEquipmentIds??[]); const [environment,setEnvironment]=useState<EquipmentProfile['environment']>(initialEquipment?.environment??'commercial_gym'); const [errors,setErrors]=useState<Record<string,string>>({}); const [saved,setSaved]=useState(false); const [theme,setTheme]=useState<ThemePreference>(()=>(localStorage.getItem(THEME_KEY) as ThemePreference)||'system');
   const t=(key:Parameters<typeof translate>[1],variables?:Record<string,string>)=>translate(locale,key,variables); const coachName=profile?.preferredName.trim()||profile?.firstName.trim()||profile?.username||'';
   useEffect(()=>{document.documentElement.dataset.theme=theme==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):theme;localStorage.setItem(THEME_KEY,theme)},[theme]);
   const changeLocale=(next:Locale)=>{setLocale(next);saveLocale(next);setDraft(c=>({...c,locale:next}))}; const updateField=<K extends keyof AthleteProfileDraft>(key:K,value:AthleteProfileDraft[K])=>{setSaved(false);setDraft(c=>({...c,[key]:value}))}; const changeUnits=(u:UnitSystem)=>updateField('unitSystem',u); const adjustHeight=(d:number)=>updateField('heightCm',Math.min(230,Math.max(120,(draft.heightCm??175)+d))); const adjustWeight=(d:number)=>updateField('bodyWeightKg',Math.round(Math.min(250,Math.max(35,(draft.bodyWeightKg??75)+d))*10)/10);
   const submitProfile=(e:FormEvent)=>{e.preventDefault();const next:Record<string,string>={};if(!draft.username.trim())next.username=t('required');else if(!/^[a-zA-Z0-9_]{3,20}$/.test(draft.username.trim()))next.username=t('invalidUsername');if(!draft.firstName.trim())next.firstName=t('required');if(!draft.birthDate)next.birthDate=t('required');setErrors(next);if(Object.keys(next).length)return;const p=saveProfile({...draft,username:draft.username.trim(),firstName:draft.firstName.trim(),lastName:draft.lastName.trim(),preferredName:draft.preferredName.trim(),displayName:draft.displayName.trim()||draft.username.trim(),locale},profile);setProfile(p);setDraft(profileToDraft(p));setView('configuration');setSaved(true)};
   const selectPreset=(env:EquipmentProfile['environment'])=>{setEnvironment(env);setSelectedEquipment([...equipmentPresets[env]])}; const toggleEquipment=(id:string)=>setSelectedEquipment(c=>c.includes(id)?c.filter(x=>x!==id):[...c,id]); const saveEquipment=()=>{const next=saveEquipmentProfile(selectedEquipment,environment,equipmentProfile);setEquipmentProfile(next);setView('configuration');setSaved(true)};
   const heightLabel=draft.unitSystem==='metric'?`${draft.heightCm??175} ${t('cm')}`:(()=>{const v=cmToFeetInches(draft.heightCm??175);return`${v.feet}′ ${v.inches}″`})(); const weightLabel=draft.unitSystem==='metric'?`${draft.bodyWeightKg??75} ${t('kg')}`:`${kgToLb(draft.bodyWeightKg??75)} ${t('lb')}`; const categories:EquipmentCategory[]=['free_weights','machines','cables','bodyweight','accessories']; const categoryKey:Record<EquipmentCategory,Parameters<typeof translate>[1]>={free_weights:'categoryFreeWeights',machines:'categoryMachines',cables:'categoryCables',bodyweight:'categoryBodyweight',accessories:'categoryAccessories'};
   const completedSteps=1+(equipmentProfile?1:0)+(loadSetupProfile?1:0); const progress=Math.round(completedSteps/3*100);
   const headerTitle=view==='home'?'RepShift':view==='workout'?(locale==='it'?'Allenamento':'Workout'):view==='configuration'?t('configuration'):view==='profile'?t('profileSetup'):view==='equipment'?t('equipmentSetup'):t('loadSetup');
   const headerSubtitle=view==='home'?t('greeting',{name:coachName}):view==='workout'?(locale==='it'?'Sessione e routine':'Session and routines'):view==='configuration'?t('configurationTitle'):view==='profile'?t('welcomeTitle'):view==='equipment'?t('equipmentTitle'):t('loadSetupTitle');
   const go=(next:View)=>{setView(next);setSaved(false)};
   const backTarget:View=view==='configuration'||view==='workout'?'home':view==='profile'||view==='equipment'||view==='loads'?'configuration':'home';

   return <main className="app-shell mobile-app-shell">
     <header className="screen-header"><div className="screen-header-row">{view!=='home'&&profile?<button className="header-action" onClick={()=>go(backTarget)} aria-label={t('back')}>‹</button>:<div className="brand-mark compact">RS</div>}<div className="screen-header-copy"><small>{headerTitle}</small><strong>{headerSubtitle}</strong></div><button className="header-action dots" aria-label={t('configuration')} onClick={()=>profile&&go('configuration')}>•••</button></div></header>

     <div className="screen-content">
       {view==='home'&&profile&&<section className="dashboard-screen"><div className="dashboard-hero"><div className="dashboard-hero-top"><div><span className="eyebrow">REPSHIFT</span><h1>{coachName}</h1><p>{t('homeMessage')}</p></div><div className="progress-ring" style={{'--progress':`${progress*3.6}deg`} as React.CSSProperties}><span>{progress}%</span></div></div><div className="progress-track"><i style={{width:`${progress}%`}} /></div><small>{completedSteps}/3</small></div><button className="home-config-card" onClick={()=>go('workout')}><span className="home-config-icon">▶</span><div><small>{locale==='it'?'ALLENAMENTO':'WORKOUT'}</small><strong>{locale==='it'?'Crea o avvia una sessione':'Build or start a session'}</strong><em>{locale==='it'?'Routine, serie, carichi e RIR in un unico flusso.':'Routines, sets, loads and RIR in one flow.'}</em></div><b>›</b></button><button className="home-config-card" onClick={()=>go('configuration')}><span className="home-config-icon">✦</span><div><small>{t('configuration')}</small><strong>{t('openConfiguration')}</strong><em>{t('homeConfigurationHint')}</em></div><b>›</b></button>{saved&&<div className="success-message dashboard-success">✓ {t('saved')}</div>}</section>}

       {view==='workout'&&profile&&<WorkoutFlow locale={locale} onExit={()=>go('home')}/>} 
       {view==='configuration'&&profile&&<ConfigurationHub locale={locale} t={t} equipmentProfile={equipmentProfile} loadSetupProfile={loadSetupProfile} onProfile={()=>go('profile')} onEquipment={()=>go('equipment')} onLoads={()=>go('loads')} onLocale={changeLocale} theme={theme} onTheme={setTheme} />}

       {view==='profile'&&<section className="app-panel"><span className="eyebrow">{t('profileSetup')}</span><h1>{t('welcomeTitle')}</h1><p>{t('welcomeBody')}</p><form onSubmit={submitProfile} noValidate><div className="form-grid"><label><span>{t('username')} *</span><input value={draft.username} onChange={e=>updateField('username',e.target.value)}/>{errors.username&&<small className="error">{errors.username}</small>}</label><label><span>{t('firstName')} *</span><input value={draft.firstName} onChange={e=>updateField('firstName',e.target.value)}/>{errors.firstName&&<small className="error">{errors.firstName}</small>}</label><label><span>{t('lastName')}</span><input value={draft.lastName} onChange={e=>updateField('lastName',e.target.value)}/></label><label><span>{t('preferredName')}</span><input value={draft.preferredName} onChange={e=>updateField('preferredName',e.target.value)}/></label><label><span>{t('birthDate')} *</span><input type="date" value={draft.birthDate} onChange={e=>updateField('birthDate',e.target.value)}/>{errors.birthDate&&<small className="error">{errors.birthDate}</small>}</label></div><div className="section-label">{t('units')}</div><div className="segmented-control"><button type="button" className={draft.unitSystem==='metric'?'active':''} onClick={()=>changeUnits('metric')}>{t('metric')}<small>kg · cm</small></button><button type="button" className={draft.unitSystem==='imperial'?'active':''} onClick={()=>changeUnits('imperial')}>{t('imperial')}<small>lb · ft</small></button></div><div className="measurement-grid"><div className="measurement-card"><span>{t('height')}</span><strong>{heightLabel}</strong><input type="range" min="120" max="230" value={draft.heightCm??175} onChange={e=>updateField('heightCm',Number(e.target.value))}/><div className="stepper"><button type="button" onClick={()=>adjustHeight(-1)}>−</button><button type="button" onClick={()=>adjustHeight(1)}>+</button></div></div><div className="measurement-card"><span>{t('weight')}</span><strong>{weightLabel}</strong><input type="range" min="35" max="250" step="0.5" value={draft.bodyWeightKg??75} onChange={e=>updateField('bodyWeightKg',Number(e.target.value))}/><div className="stepper"><button type="button" onClick={()=>adjustWeight(draft.unitSystem==='metric'?-0.5:-lbToKg(1))}>−</button><button type="button" onClick={()=>adjustWeight(draft.unitSystem==='metric'?0.5:lbToKg(1))}>+</button></div></div></div><p className="privacy-note">{t('privacyNote')}</p><button className="primary-button sticky-action" type="submit">{profile?t('updateProfile'):t('saveProfile')}</button></form></section>}

       {view==='equipment'&&<section className="equipment-premium-screen"><div className="equipment-command"><div><span className="eyebrow">{t('equipmentSetup')}</span><strong>{t('equipmentTitle')}</strong><small>{t('equipmentSetupHint')}</small></div><button onClick={saveEquipment}>✓ <span>{t('saveEquipment')}</span></button></div><div className="environment-carousel">{(['commercial_gym','home_gym','minimal'] as const).map(p=><button key={p} className={environment===p?'environment-card selected':'environment-card'} onClick={()=>selectPreset(p)}><span>{p==='commercial_gym'?'◫':p==='home_gym'?'⌂':'◆'}</span><div><strong>{t(p==='commercial_gym'?'commercialGym':p==='home_gym'?'homeGym':'minimalSetup')}</strong><small>{t(p==='commercial_gym'?'commercialGymHint':p==='home_gym'?'homeGymHint':'minimalSetupHint')}</small></div></button>)}</div><div className="equipment-inventory-heading"><div><small>{t('equipmentInventory')}</small><strong>{t('selectedCount',{count:String(selectedEquipment.length)})}</strong></div></div>{categories.map(c=><div className="equipment-category premium" key={c}><h3>{t(categoryKey[c])}</h3><div className="equipment-grid">{equipmentCatalog.filter(i=>i.category===c).map(i=><button key={i.id} className={selectedEquipment.includes(i.id)?'equipment-card selected':'equipment-card'} onClick={()=>toggleEquipment(i.id)}><span className="equipment-symbol">{i.icon}</span><strong>{t(i.nameKey as Parameters<typeof translate>[1])}</strong><span className="checkmark">✓</span></button>)}</div></div>)}</section>}

       {view==='loads'&&<LoadSetupScreen current={loadSetupProfile} t={t} onBack={()=>go('configuration')} onSave={nextDraft=>{const next=saveLoadSetup(nextDraft,loadSetupProfile);setLoadSetupProfile(next);go('configuration');setSaved(true)}}/>}
     </div>

     {profile&&<nav className="bottom-app-nav compact-main-nav" aria-label={t('mainNavigation')}><button className={view==='home'?'active':''} onClick={()=>go('home')}><span>⌂</span><small>Home</small></button><button className={view==='workout'?'active':''} onClick={()=>go('workout')}><span>▶</span><small>{locale==='it'?'Allenamento':'Workout'}</small></button><button className={view==='configuration'||view==='profile'||view==='equipment'||view==='loads'?'active':''} onClick={()=>go('configuration')}><span>⚙</span><small>{t('configuration')}</small></button></nav>}
   </main>;
 }
